### ISSUE TITLE
Getting a lack of a permissions / not typical block

### ISSUE THREAD

**Issue by shaenr** [anoduck/UFS-quackified#4]
When I attempt to view lists of grouped photos, like all photos, it will tell me that maybe some audiences ahve restriscted view of that whatever. But if I go directly to photos it will display them all normally. This is ran with a blank input link only on friends.

**Comment by shaenr** [comment]
I dumped the user names of all my friends using other tools and and just used tohose as the input. Its currently going very slow through my first friend with a massive amouint of friends i dont care about :/... We'll see how far I get.

**Comment by anoduck** [comment]
WHOA! I missed seeing this issue...My bad...let me see if I understand this correctly.

Are you saying you have access to the photos in an album directly, but cannot view them in a group as an album?

If the above is the case:
I agree that is weird, but this is an old hack I discovered a decade ago. It has to do with the book of face's weird policy restrictions, where user permissions contradict each other. For example a user has restricted public access to her photo albums, but is currently using a photo from one of those albums to share with the public on her wall. In this case in order to display the requested content, the book of face has to allow public access to the album in order to use it on her wall, while still denying public access to the entirety of the album. So, how the book of face has resolves this issue is to deny access to the link leading to the album, but allow the link leading to a particular photo which then can be used to view the other photos in the album indirectly and unintentionally. 

AND no, the script will not be able to scrape it. Because it accesses photos using the albums link and not through a solitary photo.

Yeah, the scraping process is painfully slow. Almost unusable. But if you try to speed it up, rate limit restrictions will ban you in a flash.
