### ISSUE TITLE
Stucked at login page

### ISSUE THREAD

**Issue by wankio** [anoduck/UFS-quackified#9]
https://mbasic.facebook.com/

It just pasted account information into login page but not clicked on Log in  button, tried with https://en-gb.facebook.com/ still not working

as a window user, i'm download geckodriver into my python root dir and delete geckodriver path in photo-scrape

```
Starting Scraping...
There is something wrong with logging in.
<class 'selenium.common.exceptions.NoSuchElementException'>
```

so i'm just edit button xpath into 
`driver.find_element_by_xpath("//button[contains(.,'Log In')]").click()`
and it just logged account on facebook.com (login on mbasic need auth code from email so i'm just switched to facebook.com)

but even logged

```
Starting Scraping...
There is something wrong with logging in.
<class 'selenium.common.exceptions.NoSuchElementException'>
```

still happen, i dont know this line mean for what element
`driver.find_element_by_xpath("//body[1]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/div[3]/a[1]").click()  # noqa: E501`

**Comment by anoduck** [comment]
I apologize for not having gotten to you sooner. 

---

Have you tried running it in windows' Linux emulation  container thingy-ma-bob?

---

Unfortunately, Windows compatibility was not considered during the development of the project. 

One would need Linux emulation in order to allow the script to change directories, discover files, and manipulate paths. You might consider running the script in a virtual environment such as virtualbox, vmware, or the like. 

The book of face changes its source code often to dissuade users from scraping it. I will have to give the script a test run and see if this is the case, and if it is preventing a successful login.

**Comment by anoduck** [comment]
I gave the script the aforementioned test run and did not run into any of the mentioned errors running it.
